name: material programming project

sass:
  sass_dir: _sass

root: /
collections_dir: collections

baseurl: "/~material" # the subpath of your site, e.g. /blog
url: ""

future: true

collections:
  projects:
    output: true
    order:
      - software.md
      - talks.md
      - workshops.md
      - tools-index.md
      - ktrg.md
  talks:
    output: true