name: material programming project

sass:
  sass_dir: _sass

root: /
collections_dir: collections

baseurl: "" # the subpath of your site, e.g. /blog
url: ""

future: true

collections:
  projects:
    output: true
  talks:
    output: true